### ISSUE TITLE
关于demo的问题

### ISSUE THREAD

**Issue by malongq** [Zhaoss/VideoPlayerDemo#1]
1.页面在如果停留，则会一直不停的循环播放可视区域的视频
2.播放最后一个进入全屏，播完后会直接滚动到第一条视频开始播放
3.视频在列表是播放，只要一滑动屏幕就会暂停，松开后又会重新播放

**Comment by Zhaoss** [comment]
逻辑就是如此 怎么了?

**Comment by Zhaoss** [comment]
3.视频在列表是播放，只要一滑动屏幕就会暂停，松开后又会重新播放
是播放区域滑出可视区域就会停止,  手指松开后会重新检测哪个item在可以区域 然后播放

**Comment by lihonglin810** [comment]
请问这个缓存机制是边播边缓存 还是直接缓存整个视频 还是可以选择是哪种???

**Comment by dustreading** [comment]
可以添加对m3u8视频的支持

**Comment by Zhaoss** [comment]
> 请问这个缓存机制是边播边缓存还是直接缓存整个视频还是可以选择是哪种???

边下边播时会开启两个流 一个下载流 一个缓存流,  一边下载一边缓存到本地,  在下载完成后会对视频做完整度校验,  如果你要全下载到内存中在缓存 视频过大会
OOM
