### ISSUE TITLE
视频宽高的自适应

### ISSUE THREAD

**Issue by Ximano** [Zhaoss/VideoPlayerDemo#10]
您好，大佬！我想请教下咱们这个播放器是否可以支持视频文件宽高的自适应，我看到demo中传入视频url的同时一般都要把video的width和height传入，能否不穿视频width和height，自适应视频在屏幕中显示？？

**Comment by Zhaoss** [comment]
可以使用播放器初始化一下视频 就能得到宽高了

**Comment by Ximano** [comment]
初始化一下，startPlay？具体还请大佬简单说下，或者还有没有其他方式通过一个视频url获取到视频的宽高。或者老哥，也可以见建一个群，大家使用者一起探讨和交流，非常感谢~

**Comment by Zhaoss** [comment]
调用prepare()方法 然后在OnInfoListener回调里接受视频信息

**Comment by Ximano** [comment]
还有demo中看到有raw demo.mp4的视频文件，是否支持raw下的视频呢？

**Comment by Ximano** [comment]
![image](https://user-images.githubusercontent.com/9362546/53620581-73c58f00-3c2e-11e9-8fc0-4f7a8b3fe7e7.png)
RawDataSourceProvider是我重写的，但是无法直接播放呢，我的api使用的不对么？
