### ISSUE TITLE
m3u8

### ISSUE THREAD

**Issue by JD-CP** [Zhaoss/VideoPlayerDemo#17]
m3u8 视频播放一直失败，希望可以提供 m3u8 支持。

**Comment by Q461339779** [comment]
您使用的这个框架不支持m3u8的问题解决了吗

**Comment by JD-CP** [comment]
没有解决。我换了其他的播放器，做了类似抖音的播放效果。如果有需要，可以联系我。

**Comment by Zhaoss** [comment]
更新了so库 支持了大部分视频格式 优化了下载缓存速度
